//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxiEntities : DbContext
    {
        public taxiEntities()
            : base("name=taxiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brand { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<driverCar> driverCar { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
