//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverCar
    {
        public long id { get; set; }
        public Nullable<long> car { get; set; }
        public Nullable<long> driver { get; set; }
    
        public virtual car car1 { get; set; }
        public virtual driver driver1 { get; set; }
    }
}
