//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string startStreet { get; set; }
        public string endStreet { get; set; }
        public decimal price { get; set; }
        public string startHouse { get; set; }
        public string endHouse { get; set; }
        public long driver { get; set; }
        public Nullable<long> user { get; set; }
        public Nullable<long> status { get; set; }
    
        public virtual driver driver1 { get; set; }
        public virtual status status1 { get; set; }
        public virtual user user1 { get; set; }
    }
}
